version: 3
endpoint: https://ws-dev.hasura.app
admin_secret: X5O08fvRanb6WomI1UGVfh0EZuB0BnxKPYQhpmsYOK1wPvHV8IieeuP7FSbgEOUf
metadata_directory: metadata
actions:
  kind: synchronous
  handler_webhook_baseurl: http://localhost:3000
